### ISSUE TITLE
Fix the "Admin" dropdown placement

### ISSUE THREAD

**Issue by PixelPoncho** [zoouofc/ewma#13]
Not 100% certain what the issue with this, however, its likely a styling change that needs to be made to realign the placement of the dropdown when it appears

Note: it has to making content with the hitbox of "Admin" else when you move your cursor to interact with the dropdown, it will disappear

![image](https://user-images.githubusercontent.com/33527005/110284392-fb250600-7f9e-11eb-99bc-ef1fef481a61.png)

**Comment by bufutda** [comment]
This was resolved by https://github.com/zoouofc/ewma/pull/10
